### ISSUE TITLE
Liste des offres : gestion des filtres

### ISSUE THREAD

**Issue by Wamibee** [Ganatrade/www#9]

**Comment by neerfix** [comment]
[Get all offers by UserID](https://doc.ganatrade.xyz/docs/api/reference/API.v1.yaml/paths/~1users~1%7BuserId%7D~1offers/get)

[Get all offers by CategoryId](https://doc.ganatrade.xyz/docs/api/reference/API.v1.yaml/paths/~1offers~1categories~1%7BcategoryId%7D/get)
